#!/bin/env python3
# Created by atbswp v0.3.1 (https://git.sr.ht/~rmpr/atbswp)
# on 19 Jan 2022 
import pyautogui
import time
pyautogui.FAILSAFE = False

time.sleep(5)
pyautogui.keyDown('w')
time.sleep(10)
pyautogui.keyUp('w')
pyautogui.keyDown('s')
time.sleep(10)
pyautogui.keyUp('s')