#!/bin/env python3
# Created by atbswp v0.3.1 (https://git.sr.ht/~rmpr/atbswp)
# on 19 Jan 2022 
import pyautogui
import time
pyautogui.FAILSAFE = False

selfcast_key = 'e'
spell_key = '9'
rest_key = '0'

pyautogui.keyDown(spell_key)
pyautogui.keyUp(spell_key)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(1.5)
pyautogui.keyDown(selfcast_key)
pyautogui.keyUp(selfcast_key)
time.sleep(0.5)

pyautogui.keyDown(rest_key)
pyautogui.keyUp(rest_key)
time.sleep(60)